language: java
jdk:
- oraclejdk11
addons:
  sonarcloud:
    organization: senoramarillo
    token:
      secure: X4PRXZNFoY1Syu58bOySqqZolf/9ccXkEm5eMPb/RNHbkHiRIOIwZjDFXwnGgnKzCoil329DiBy8g+HFvMCSNv2HyfMzaAOmcuL55JVvKdnBfWoVqXIXFsz7H0GyubMbPMkHjo49Fc5zx18FcjTcrAHbdmGmb98i8x8sk5Ma4CzWfbVmlqX5Qd50qYGhE8ikIEkiRnnSRjiRXIHJ/y3pFyCBoHzfIFFTj9kM9B+mQYTfbnfDfJBLr5/+xV2B1/ZUP9nSRm5pY/EpsWlfhJS28dy1B1K0dfsH9Wrd5u8NkJgrmIMguioRHFVYpf6S9vphX9Tu5Z9dWQWIppv4xDuD8sBWNe3uju1YJ4t/WqngiPjmxUjfsmVO0KJv8F4eVAd3QXYpaDgqF7HWL9g1KGIDIDDkGdvso2G+U4siZAm6gmzZpThmM8ubUjh2KpBWkD2gxJGT9CmcnC1aVeMcZROXKYqggmm40Vv1awuFbBCftf8iPpXP/HZYXOpES1iUw3CIHYGgAd/SXVPSWIcXniq7N79k0jqwLPhuDvYQ5D0As6u/xHatMgJ8MZ+pPcie2ck+tEt3lJ+FqQtmlepY68ZQ+mSMy6dckn6xC8XHoox4swwviobUEJw0+10S8isstmONs/UXn6p1nv4gnFaPDrJPpiqQ65vf1GCg4OiiAcemvJ8=
#deploy:
#  provider: heroku
#  app: roommgmt-react
#  api_key:
#    secure: pchJgB5duLpbIMmqlm3+WiHRIOGzuJsGZzzFAERVF9R1yQT/HieaK4EiY/xe5fVIq6yzP9KqzDU8LHx7UecvDlhf3x7mCAr84cgau7awoNDolbp36Og+/OYLtenrXOHB4xT/u6l1qyqFjQoV8FY+6pqOJdHe2Aie46jX8Rz0bzad3sDCXjyO6RGEst/7PLSdOC9vlngbAZrJGcwq1Ql7YwFkwhUSu9fY58OcUU5cC/QZkY7FYmbIIaer7aJ7LV+UHgsgBe3r9psTiZKdmT514SoH75CXMpjJhjXTXvNdC7nFlQnhSddszwljU1RoK1Cau5XKPjk3EY3wJVBNop8nt4JhS9BNK4X/VIcc8zpZZ95Ta2FAFX13B9NCpnRgthdDTuIW24B7/HMiHVLbwHd4EpdXxiRMOI1NJMxa1LagVnyGRhag/TKZ377xFtypZdzVnzFTpqrIAX41mwvz+yDAmTZWR+WAXoNCpVR8tuXwhiBwEHHSbo52q1PToy4z5JWcdinO02XOx+LqflqwrXQBJeMsRVtzQ3vHogxqrJdgS6tNTXE7JcFWFIn81lIMsJue1PhMRDy854EP3ifNWqXzB+OouF83YAMhFL5CLTpo5RmpCW/RBq/ilyYXm2gidbA7s0AtYPFYwhTxF9K/KX3se8L9Bo4zEswapbpgAor5hYc=
#  on:
#    all_branches: true
notifications:
  email:
    on_success: never
    on_failure: never
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=senoramarillo_roommgmt-react
before_install:
- chmod +x mvnw
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn clean test jacoco:report coveralls:report
env:
  global:
    secure: zxgaj7sczkPg+WUm4iDwcaUI+ScB6m52zcXq9hN0F91/YdaN5fxNYnCOM61xHwK1nZtfz0nKAVAte6qvlhwvCO73cXXQKRYoFLHYiRjrkWsWqJZngx32AOgWfQc+FXNS6UMEevtRvYfzhqhSAfuSF8GGblTIbpqB3H92GzxZApwLQd+xHMmdxN36o1R2ssnBHvSxPNZb570lsGqnsqWWklXXaXvd3tifhCiRIXxZdTkw/C3fvm7ZdevPNDTisaFVY6zoev85bL42GMz8GKzNQll/QSPws8jRPDIdh5HAmgfq6Yww6YYD9yZIstghP5cf7riSwDE4FDCOUXo77CV3Ei+kdGmSDEaNgsij5zUet6JsNm1Rs8Bj/Xye365M/Tv4d5qKbMuOC12gIdvmaKH22dN9YABPs9pDj3Qs0gXVrdlVf1f6z+EXT78+hYgwmhgSJWNPRovaazf6tDofDj1Y2CGTq+knaZmxpYsX4HdbBncgZdEnLiPN0dTqeICzr9s6qCGd4sxFgZQlvNXg4uJxWpmuqSJ8oAgIQ/h4t/2mWdSfoJAP+5IjOh9NfVBwJpphPaTVk8/3p3f9u7COeN1gAMTNpDDYftFEI+1ginLr1lFEIiIiKDXlx4ebLeXo2XwLEzjeQxMktR7xrOsCS2h6Fq/xeUk5JJNdA0AXdfa5Kio=