language: java
jdk:
- oraclejdk11
addons:
  sonarcloud:
    organization: senoramarillo
    token:
      secure: Jr5Sh+gOfO+8Cmzspe9iKclgz9sjBSd0XFEW3hvMZm93egHyO8iawSzP44iJCIZzqCMgi7ifrzbPtqsgtnAY/jsPYHcS7KLhreXD5ROoG5UrFiRxYv01zclxIgZua6mhvaxHGOi8h2wJ9G4TLCUTG2fwa2jCoiGXI9Gf4+BgUFDM88JzhnWen5kbBYb5ZtKain1QqCPkzPtTLhFwofgL8N2F0I+LW2K4mq12y5oE52S3nH0Fr7aiXdbA79jlgi7iXSN8sJ1oMVdT2S8RNeD3TsxKwTlL+MpLJNw6Yp7Wjon0dVgHnY/TreDxnHnkgEkcBQdOEtDEY3Q0GKUBj1jXU+Rgz1NoqNb0g/hdt7Y9dQ+swsdxvvV0gT43Ojow7N6oOd6/p9HUbiF2wLTepdaLfXLJrgk4TGl85FBnAP3FeEgDxK+YgHNlqvl7Fa+1CEFGf83aVzUeBw5/dtkgdqLai4M99fKa3Vt3Uc5gqs8zbwzdndis4zXpLe7GkC4Mjyk6F2rTV5LrUTgjXzTkBcW911GRrYDRz3vZRP5HNCaa86DmTt7jG50jUYZILP8RN3zf2zhgTOKXT+JbOtSCvXWUoCvK3sv+eDa+n/maIz90aImu8IYc87TQtM33Sh3isgJ0gTlly2c0mGXTXh40L9uxq2Wm1ludAFh/7zXh6BlSDso=
deploy:
  provider: heroku
  app: roommgmt-react
  api_key:
    secure: pchJgB5duLpbIMmqlm3+WiHRIOGzuJsGZzzFAERVF9R1yQT/HieaK4EiY/xe5fVIq6yzP9KqzDU8LHx7UecvDlhf3x7mCAr84cgau7awoNDolbp36Og+/OYLtenrXOHB4xT/u6l1qyqFjQoV8FY+6pqOJdHe2Aie46jX8Rz0bzad3sDCXjyO6RGEst/7PLSdOC9vlngbAZrJGcwq1Ql7YwFkwhUSu9fY58OcUU5cC/QZkY7FYmbIIaer7aJ7LV+UHgsgBe3r9psTiZKdmT514SoH75CXMpjJhjXTXvNdC7nFlQnhSddszwljU1RoK1Cau5XKPjk3EY3wJVBNop8nt4JhS9BNK4X/VIcc8zpZZ95Ta2FAFX13B9NCpnRgthdDTuIW24B7/HMiHVLbwHd4EpdXxiRMOI1NJMxa1LagVnyGRhag/TKZ377xFtypZdzVnzFTpqrIAX41mwvz+yDAmTZWR+WAXoNCpVR8tuXwhiBwEHHSbo52q1PToy4z5JWcdinO02XOx+LqflqwrXQBJeMsRVtzQ3vHogxqrJdgS6tNTXE7JcFWFIn81lIMsJue1PhMRDy854EP3ifNWqXzB+OouF83YAMhFL5CLTpo5RmpCW/RBq/ilyYXm2gidbA7s0AtYPFYwhTxF9K/KX3se8L9Bo4zEswapbpgAor5hYc=
  on:
    all_branches: true
notifications:
  email:
    on_success: never
    on_failure: never
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=senoramarillo_roommgmt-react
before_install:
- chmod +x mvnw
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: bnb0E0M0eWM9RnG2KZqZuWLq/IBrp0yZoQJ0y/BpWyWxGIy9132gRs6AJP20d4v6o/QmTy5sLmDWaLstll7o1Cnw8/rR77rrhxEXqRW6tBfnd8EcMw1hi49S2U1l+JIA7JY4CNOV1WIy08sGJJHWDN3XSU0rrFvEmqt0RLt+Xnr+OE6dimjbt+8aDd1wZffIqAsL8L30ZbEN/6r+depzb0zD46U5nTfuALKi+iPqpk4M6heV9vsG6rsWorv7442mr+wVLbMx9nCi5h/Ato2NEctTZot7mhMx2DPAt/v5XN85iHzapaaN3/6YhP3pjTABAA231nV6wL1WHIEYRjf/urpRzQA0dM2AhiYsQF1A7OPF0QGbX7zoHFGKeFJ9wKl8rbMWZLUSdvR99fTq6Ww16fYB7nvvQaakawyvXviqvv9kWTufXhm+N6wd+UaxgQ1EmvAl8PPhtcEbyRy4F7aTykuH5S0k7Ta/KShSd+8Eea01FoE2lgiJXdtXmeZHoufe+KON9NJTOe6864CMNpBbiAA7zYCDkH41BnNJPOstZncyOdSRcQ1TsgYDf1TKWRu5nbr9+yFuLwVr+nhb4CtkNuRBLIacVdJpogO4REStFejkVhBPG2F1YWgbs3EByzo9Uofece3QNZka4+XjcLTrxFgs47DQeFO9wPAF1dvPdcM=
