language: java
jdk:
- oraclejdk11
addons:
  sonarcloud:
    organization: senoramarillo
    token:
      secure: QKlcHKlN1NAgJ+qaWB9oEWS//B//IwCe7EM/GrS2J+T/vatB6rb0V1QLOodynYxdVCr316xZLryTFxXTRrCT4EKly6mlJGjZgCjn1NoBiqqCDnXIjSebQQHTAXOjeMYY2VIR+HDCg0+ARJdfneDigrCoR5/oRgT7dCJgeSt7qoYX53fg21gdf48ByCA23ZGFTfamwlmZKCK5Bpvi+Q9IelC83T3IZECUi/iT0aGTO0/nMBgbyu5C7PY6emlxRetFcQy+1qJbnwxceoJDzWUrUahzbgaCkHNMmIAUFItPOYXLmIaoJETP/Fn5PP/tosaWecrEfsYdPjVGPuGdGvQsTDnMxfM3LP6BOIFdJ6jkPqy5HS7Stak6lqrxp/NccrKd35sYG/cgHZEaxqOT+i6iKThKKTAtNIpiPWVTomzDTPTZxJFbMnDy9aRc30vis0I9WxMSRjdTEr81csTL8gvyJYLHLRHZJRUICIvbXl/kZO/8aDurt3uF7+y+H/c/ZsYAhq84wfd2NZ4aALEst7k7AB9p4HfQhgWad6RxxL9zwo5V2ohbta3tqZof1fJHQ3KVhXKAUmX+vZ3bUfhMhKJHHZis19bNgAcLsvITqbGLYMSS48IuLALpxiMGwP6To0tAx8VnNfep6hJ91qQxFuD6SgxFWdKfNzb24svQFFxNq24=
#deploy:
#  provider: heroku
#  app: roommgmt-react
#  api_key:
#    secure: pchJgB5duLpbIMmqlm3+WiHRIOGzuJsGZzzFAERVF9R1yQT/HieaK4EiY/xe5fVIq6yzP9KqzDU8LHx7UecvDlhf3x7mCAr84cgau7awoNDolbp36Og+/OYLtenrXOHB4xT/u6l1qyqFjQoV8FY+6pqOJdHe2Aie46jX8Rz0bzad3sDCXjyO6RGEst/7PLSdOC9vlngbAZrJGcwq1Ql7YwFkwhUSu9fY58OcUU5cC/QZkY7FYmbIIaer7aJ7LV+UHgsgBe3r9psTiZKdmT514SoH75CXMpjJhjXTXvNdC7nFlQnhSddszwljU1RoK1Cau5XKPjk3EY3wJVBNop8nt4JhS9BNK4X/VIcc8zpZZ95Ta2FAFX13B9NCpnRgthdDTuIW24B7/HMiHVLbwHd4EpdXxiRMOI1NJMxa1LagVnyGRhag/TKZ377xFtypZdzVnzFTpqrIAX41mwvz+yDAmTZWR+WAXoNCpVR8tuXwhiBwEHHSbo52q1PToy4z5JWcdinO02XOx+LqflqwrXQBJeMsRVtzQ3vHogxqrJdgS6tNTXE7JcFWFIn81lIMsJue1PhMRDy854EP3ifNWqXzB+OouF83YAMhFL5CLTpo5RmpCW/RBq/ilyYXm2gidbA7s0AtYPFYwhTxF9K/KX3se8L9Bo4zEswapbpgAor5hYc=
#  on:
#    all_branches: true
notifications:
  email:
    on_success: never
    on_failure: never
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=senoramarillo_roommgmt-react
before_install:
- chmod +x mvnw
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn clean test jacoco:report coveralls:report
env:
  global:
    secure: zxgaj7sczkPg+WUm4iDwcaUI+ScB6m52zcXq9hN0F91/YdaN5fxNYnCOM61xHwK1nZtfz0nKAVAte6qvlhwvCO73cXXQKRYoFLHYiRjrkWsWqJZngx32AOgWfQc+FXNS6UMEevtRvYfzhqhSAfuSF8GGblTIbpqB3H92GzxZApwLQd+xHMmdxN36o1R2ssnBHvSxPNZb570lsGqnsqWWklXXaXvd3tifhCiRIXxZdTkw/C3fvm7ZdevPNDTisaFVY6zoev85bL42GMz8GKzNQll/QSPws8jRPDIdh5HAmgfq6Yww6YYD9yZIstghP5cf7riSwDE4FDCOUXo77CV3Ei+kdGmSDEaNgsij5zUet6JsNm1Rs8Bj/Xye365M/Tv4d5qKbMuOC12gIdvmaKH22dN9YABPs9pDj3Qs0gXVrdlVf1f6z+EXT78+hYgwmhgSJWNPRovaazf6tDofDj1Y2CGTq+knaZmxpYsX4HdbBncgZdEnLiPN0dTqeICzr9s6qCGd4sxFgZQlvNXg4uJxWpmuqSJ8oAgIQ/h4t/2mWdSfoJAP+5IjOh9NfVBwJpphPaTVk8/3p3f9u7COeN1gAMTNpDDYftFEI+1ginLr1lFEIiIiKDXlx4ebLeXo2XwLEzjeQxMktR7xrOsCS2h6Fq/xeUk5JJNdA0AXdfa5Kio=