#language: java
#sudo: true
#jdk:
#- oraclejdk11
#addons:
#  sonarcloud:
#    organization:
#    token:
#      secure:
#deploy:
#  provider: heroku
#  app:
#  api_key:
#    secure:
#  on:
#    branch: master
#notifications:
#  email:
#    on_success: never
#    on_failure: never
#script:
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=
#before_install:
#- chmod +x mvnw
#after_success:
#- bash <(curl -s https://codecov.io/bash)
