language: java
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: senoramarillo
    token:
      secure: r7RW9ytlUYFwppTFrAGHoE48eFrYMJUSq2ZkeXJqiWjw+zfrn7txSzPu++7tyZ4ptX5/VmHPnX1GwbSl/bdBKBeAny4NAXdfcQV6zl2P93E0y3uY1cl1YQMKhjgmIAGTfVPozns6UDej1HVZ7WEBooguOmpLl1qJfKH2ZrWodzLsYes8LJ/IS4Ift7EEEqbEsWQIy0NsWiJYBV2dK9Z4UkPc63hJ3C5UloHWg43mPJBVp5gPzjk/GekPFC4BCS7KkbKA/kaE2zniAuYesFhtF8CcEWeq9TYCgDrh7GJtKkFigNBpFiVeWnnPAbsnmXz86dmlCHUdbAJm0yAj4O4SA6JJ2TZ54MyYQJuEIYTWw6bf9hO3DHKQe2+DujQFi2VPQpFWJTXihQnfkrzAE2S5a0/bSyNuFgo0BEgrlHZaQi9e6rOUP5Rp9mLfJmL1aqOwz5cMdDSm0zvamzWeZiOua2DSXxCKA0ghYz62jUqRi7RvufpCbHjZPy5mvOU3XJLo4R/Bnjz+aTTSJx+KGXAF+DP+dUHjI95KdoS4HEwvjh/QoMVbSzm2TS/4TWwkRoZi9Bm9c5Ed9U7fdg9BfHLONod+MrBarG3I+i1EubcRE0xCwUp2rvN2UXWfqNap1TlNXBqLzE0skkkz95Hbcusz3q055xEhLVwZpmSq5H0luNs=
#deploy:
#  provider: heroku
#  app: roommgmt-react
#  api_key:
#    secure: pchJgB5duLpbIMmqlm3+WiHRIOGzuJsGZzzFAERVF9R1yQT/HieaK4EiY/xe5fVIq6yzP9KqzDU8LHx7UecvDlhf3x7mCAr84cgau7awoNDolbp36Og+/OYLtenrXOHB4xT/u6l1qyqFjQoV8FY+6pqOJdHe2Aie46jX8Rz0bzad3sDCXjyO6RGEst/7PLSdOC9vlngbAZrJGcwq1Ql7YwFkwhUSu9fY58OcUU5cC/QZkY7FYmbIIaer7aJ7LV+UHgsgBe3r9psTiZKdmT514SoH75CXMpjJhjXTXvNdC7nFlQnhSddszwljU1RoK1Cau5XKPjk3EY3wJVBNop8nt4JhS9BNK4X/VIcc8zpZZ95Ta2FAFX13B9NCpnRgthdDTuIW24B7/HMiHVLbwHd4EpdXxiRMOI1NJMxa1LagVnyGRhag/TKZ377xFtypZdzVnzFTpqrIAX41mwvz+yDAmTZWR+WAXoNCpVR8tuXwhiBwEHHSbo52q1PToy4z5JWcdinO02XOx+LqflqwrXQBJeMsRVtzQ3vHogxqrJdgS6tNTXE7JcFWFIn81lIMsJue1PhMRDy854EP3ifNWqXzB+OouF83YAMhFL5CLTpo5RmpCW/RBq/ilyYXm2gidbA7s0AtYPFYwhTxF9K/KX3se8L9Bo4zEswapbpgAor5hYc=
#  on:
#    all_branches: true
notifications:
  email:
    on_success: never
    on_failure: never
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=senoramarillo_roommgmt-react
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean test jacoco:report coveralls:report
env:
  global:
    secure: zxgaj7sczkPg+WUm4iDwcaUI+ScB6m52zcXq9hN0F91/YdaN5fxNYnCOM61xHwK1nZtfz0nKAVAte6qvlhwvCO73cXXQKRYoFLHYiRjrkWsWqJZngx32AOgWfQc+FXNS6UMEevtRvYfzhqhSAfuSF8GGblTIbpqB3H92GzxZApwLQd+xHMmdxN36o1R2ssnBHvSxPNZb570lsGqnsqWWklXXaXvd3tifhCiRIXxZdTkw/C3fvm7ZdevPNDTisaFVY6zoev85bL42GMz8GKzNQll/QSPws8jRPDIdh5HAmgfq6Yww6YYD9yZIstghP5cf7riSwDE4FDCOUXo77CV3Ei+kdGmSDEaNgsij5zUet6JsNm1Rs8Bj/Xye365M/Tv4d5qKbMuOC12gIdvmaKH22dN9YABPs9pDj3Qs0gXVrdlVf1f6z+EXT78+hYgwmhgSJWNPRovaazf6tDofDj1Y2CGTq+knaZmxpYsX4HdbBncgZdEnLiPN0dTqeICzr9s6qCGd4sxFgZQlvNXg4uJxWpmuqSJ8oAgIQ/h4t/2mWdSfoJAP+5IjOh9NfVBwJpphPaTVk8/3p3f9u7COeN1gAMTNpDDYftFEI+1ginLr1lFEIiIiKDXlx4ebLeXo2XwLEzjeQxMktR7xrOsCS2h6Fq/xeUk5JJNdA0AXdfa5Kio=