language: java
sudo: true
jdk:
- oraclejdk11
addons:
  sonarcloud:
    organization: senoramarillo
    token:
      secure: JgA6quhjzmOCswPkWQao1jgMlh5RIN9meWo0QnZEuZMqXWwGW7y20hHduFhmLh8EJNlAnZybNkpxsp9fr20mXj9WP7zyqh7+NaYO4rBidqHrOL8IVgv6vJMvKI9KnoLaS+VnSNVNn/Ka5KlnRIFskJUj2Ca576+t1wPy/0+yi+69O2XHCwkXqys2g3VhHUNvnX1+RJCi2H1/Ss49cNlhHTOQRmgEk956koFDNRhr4V8EUjM2Ut2uhjTxgiVeKCZISiSjahIRjczFlJvYkJaLBJVAGMbY+aMLDx0D471YUCrcBTwZH6qnKYx/QoczdA32RFukKhv5LsTGDNWTmAIEC0pqObOokNO91FnWZW1rjus/jppkFU2d20pTNBu7BT1XpCQvWWvQqZ+oifMHqzOhczaPK6mpIpLOnb8V10jAodiQDg9HfxarI+Zxo5pOOOQmkCSNgciGyl07fYeZmft1mTFkCoBQbHRuW/HoaWEUV/20eKWUz0SAhe2TZErHm1bDz809xw5ty2BKW9yEYi2AwsoRzn4aEhNsLFUKKnhRabrml3XoisMuRMmmnixn7CMM5IM1G8eFVtJ59TKD8kGuKzuqRWY9ENBdSKAx68DV/aUixPmaa4k+hNv93Ttn9KKo1ZNwqI+b4ZlQANuXYfpqE6wucopVqdn7ljEHAXsnxeM=
deploy:
  provider: heroku
  app: roomgmt-react
  api_key:
    secure: pchJgB5duLpbIMmqlm3+WiHRIOGzuJsGZzzFAERVF9R1yQT/HieaK4EiY/xe5fVIq6yzP9KqzDU8LHx7UecvDlhf3x7mCAr84cgau7awoNDolbp36Og+/OYLtenrXOHB4xT/u6l1qyqFjQoV8FY+6pqOJdHe2Aie46jX8Rz0bzad3sDCXjyO6RGEst/7PLSdOC9vlngbAZrJGcwq1Ql7YwFkwhUSu9fY58OcUU5cC/QZkY7FYmbIIaer7aJ7LV+UHgsgBe3r9psTiZKdmT514SoH75CXMpjJhjXTXvNdC7nFlQnhSddszwljU1RoK1Cau5XKPjk3EY3wJVBNop8nt4JhS9BNK4X/VIcc8zpZZ95Ta2FAFX13B9NCpnRgthdDTuIW24B7/HMiHVLbwHd4EpdXxiRMOI1NJMxa1LagVnyGRhag/TKZ377xFtypZdzVnzFTpqrIAX41mwvz+yDAmTZWR+WAXoNCpVR8tuXwhiBwEHHSbo52q1PToy4z5JWcdinO02XOx+LqflqwrXQBJeMsRVtzQ3vHogxqrJdgS6tNTXE7JcFWFIn81lIMsJue1PhMRDy854EP3ifNWqXzB+OouF83YAMhFL5CLTpo5RmpCW/RBq/ilyYXm2gidbA7s0AtYPFYwhTxF9K/KX3se8L9Bo4zEswapbpgAor5hYc=
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: never
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=senoramarillo_roommgmt-react
before_install:
- chmod +x mvnw
after_success:
- bash <(curl -s https://codecov.io/bash)
