language: java
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: senoramarillo
    token:
      secure: PvrLom4co9ki0L5Y0qDebsh2QlsSKozxP6ec+LzkmAPd3RNxfU/a159ou245PBt4b2cHDlH0X7FFKBV/vH3XQG+rrv/8QtjkRpjAZHzmVLKulFPiMjIoYHBW0dPFccMByUvwi4Zm2TVYwoxbsXKJS9g9sqLs6vJqNi2KIiK1M3uhQPT3g9PL7XbG+e9IHwPGCCL4omI2PoJg+jserhagc6ECtuYAvvcMMAWFnIOGtBM4xGRT1lD76zIo6EeRRmSR0uY+8WBAI2xxYJN6xkCAYU6HwJdgzeSrREwkkYIxG9L6Uz7rNE2I/6pRMP6UpPOgTLP8TUzCxiisU0gOAe7lHQWeJWMB26D5G7Wzmdk5DXJHOps7CacUoSEGcyTf1qdSqGxhTbl7gM1kWZ7XUv/0DpsjtSiclQ7Hh34Iewau6P0Zqd8wqb9VjHOVvAclR4n+wzXtTMjGpDUoHqf6vd5IZMPkRHXGBekdOAqNm+h1+fjiuKeH3p0rhfPGb87Pf9ptQ7l1+8nZ+HXkv1NdKmPvmmnxu2XVw6dBaEAIh9DoHaRhwtLEpJ7LQIUKOaWAvXH1OH1CMkaWKBCslGWoezSPw084pfZdPYxwDGJkMW4pRsteEvoxzASPaGB2UwWjNsTBA0c02GpkOdeQ9jY/Sp+GHsDRYYW4qIbOFedwztYYoIc=
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: roommgmt-react
  api_key:
    secure: OQkn66hJRU1e5wYSPMADrL1JDlNP8++5BU0V0ukyZOG/fbu4x7byOpG/RI8WydIrJw1HdU+BA4mLxhPqEniaKlBab20GkLNIXgWGv0euQ1CPhoptJMRlKgLgdVx0RF9ffSHjtmmwq3s1a0ll/8rkbomRHwiy6q4tzf58wx3sP7RlfunhVPlu7gnsnzjwveFa0mvDAFJusgQRlsVJUV30HcRiZdbFqIBe52TQ6S2g0sfYELjhiK5153du+vpGsXNPuX3FJjw8keYfaO8WiKgRhP7opUKcDIEGwhoIGdYnnvKgfYWaz7MJ99EQMzYrmxotGNyYhWpWH+TSzQ2o4TOx79S5CYGSem1V6CW6r3wztjnBbkj6PNSBC9nffgufL/zXcO96LNgaleN3TXHmNgxclhIQBXOwUFNNxvYGH96ufPGmSfbG0pd1niwDXWZxtVYw2sCghZawCEICnOUdPVxs/2Er6o08Ni2xMTR5+oF2AGAW0WnAv4R/I91AUa3GUn/M9iiAXN6oRVzN0d5nncoq/owLxM67P4pgB6tIHx1s1iI3oHBru67oKlRloKRNqrYzP+b9yQgDK1Xis7Y7W7vby0Y3zsA9Z5xG65TdqsXNvLHJgBNf2lOrl5yzVa3JklbVXOoFC3PAZtQhaleq7QbvOwLnS/qPDYfnV9a0DrETB8E=
  on:
    all_branches: true
notifications:
  email:
    on_success: never
    on_failure: never
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=senoramarillo_roommgmt-react
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean test jacoco:report coveralls:report
env:
  global:
    secure: zxgaj7sczkPg+WUm4iDwcaUI+ScB6m52zcXq9hN0F91/YdaN5fxNYnCOM61xHwK1nZtfz0nKAVAte6qvlhwvCO73cXXQKRYoFLHYiRjrkWsWqJZngx32AOgWfQc+FXNS6UMEevtRvYfzhqhSAfuSF8GGblTIbpqB3H92GzxZApwLQd+xHMmdxN36o1R2ssnBHvSxPNZb570lsGqnsqWWklXXaXvd3tifhCiRIXxZdTkw/C3fvm7ZdevPNDTisaFVY6zoev85bL42GMz8GKzNQll/QSPws8jRPDIdh5HAmgfq6Yww6YYD9yZIstghP5cf7riSwDE4FDCOUXo77CV3Ei+kdGmSDEaNgsij5zUet6JsNm1Rs8Bj/Xye365M/Tv4d5qKbMuOC12gIdvmaKH22dN9YABPs9pDj3Qs0gXVrdlVf1f6z+EXT78+hYgwmhgSJWNPRovaazf6tDofDj1Y2CGTq+knaZmxpYsX4HdbBncgZdEnLiPN0dTqeICzr9s6qCGd4sxFgZQlvNXg4uJxWpmuqSJ8oAgIQ/h4t/2mWdSfoJAP+5IjOh9NfVBwJpphPaTVk8/3p3f9u7COeN1gAMTNpDDYftFEI+1ginLr1lFEIiIiKDXlx4ebLeXo2XwLEzjeQxMktR7xrOsCS2h6Fq/xeUk5JJNdA0AXdfa5Kio=